version: '3.4'
services:
  varnish:
    image: keopx/varnish:${VARNISH_VERSION}
    container_name: "${PROJECT_NAME}_varnish"
    network_mode: traefik_default
    environment:
      - VARNISH_PORT=${VARNISH_BACKEND_PORT}
      - VARNISH_MEMORY=${VARNISH_MEMORY}
      #   Next values only works with default default.vcl file.
      - VARNISH_BACKEND_IP=${PROJECT_NAME}_web
      - VARNISH_BACKEND_PORT=${VARNISH_BACKEND_PORT}
    labels:
      - 'traefik.port=80'
      - 'traefik.backend=${PROJECT_NAME}_varnish'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.varnish.localhost'
  web:
    image: keopx/apache-php:${PHP_VERSION}
    container_name: "${PROJECT_NAME}_web"
    network_mode: traefik_default
    volumes:
      - ${WEB_DATA_DIR}:/var/www/html # Data.
      ## SSH support. Uncomment environment -> # - SSH_AUTH_SOCK=/ssh-agent
      - ${SSH_AUTH_SOCK}:/ssh-agent
    environment:
      ## Use webroot directory. i.e: /web for drupal scaffolding.
      - WEB_ROOT
      ## SSH support. Uncomment volumes -> # - ${SSH_AUTH_SOCK}:/ssh-agent
      - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /var/www/html
    labels:
      - 'traefik.port=80'
      - 'traefik.backend=${PROJECT_NAME}_web'
      - 'traefik.frontend.rule=HostRegexp:${PROJECT_URL}, {subdomain:[^.]+}.${PROJECT_URL}'
  mysql:
    image: keopx/${MYSQL_TYPE}:${MYSQL_VERSION}
    container_name: "${PROJECT_NAME}_${MYSQL_HOST}"
    network_mode: traefik_default
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  redis:
    image: keopx/redis:${REDIS_VERSION}
    container_name: "${PROJECT_NAME}_redis"
    labels:
      - 'traefik.backend=${PROJECT_NAME}_redis'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.redis.localhost'
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    network_mode: traefik_default
    environment:
      - PMA_USER=${MYSQL_ROOT_USER:-root}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=${PROJECT_NAME}_${MYSQL_HOST}
    labels:
      - 'traefik.backend=${PROJECT_NAME}_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.pma.localhost'
  mail:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    network_mode: traefik_default
    labels:
      - 'traefik.backend=${PROJECT_NAME}_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.mailhog.localhost'
