version: '3'
services:
  varnish:
    image: keopx/varnish:${VARNISH_VERSION}
    container_name: "${PROJECT_NAME}_varnish"
    network_mode: traefik_default
    #  volumes:
    #    - ./config/varnish/${VARNISH_VERSION}/default.vcl:/etc/varnish/default.vcl
    ## mattiasgeniar file: https://github.com/mattiasgeniar/varnish-4.0-configuration-templates
    # - ./config/varnish/${VARNISH_VERSION}/drupal-template.vcl:/etc/varnish/default.vcl
    ## Niteman file: https://github.com/NITEMAN/varnish-bites/blob/master/varnish4/drupal-base.vcl
    # - ./config/varnish/${VARNISH_VERSION}/drupal-base.vcl:/etc/varnish/default.vcl
    environment:
      - VARNISH_PORT=${VARNISH_BACKEND_PORT}
      - VARNISH_MEMORY=${VARNISH_MEMORY}
      #   Next values only works with default default.vcl file.
      - VARNISH_BACKEND_IP=${PROJECT_NAME}_web
      - VARNISH_BACKEND_PORT=${VARNISH_BACKEND_PORT}
    labels:
      - 'traefik.port=80'
      - 'traefik.backend=${PROJECT_NAME}_varnish'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.varnish.localhost'
  web:
    image: keopx/apache-php:${PHP_VERSION}
    container_name: "${PROJECT_NAME}_web"
    network_mode: traefik_default
    volumes:
      - ${WEB_DATA_DIR}:/var/www/html # Data.
      ## SSH support. Uncomment environment -> # - SSH_AUTH_SOCK=/ssh-agent
      - ${SSH_AUTH_SOCK}:/ssh-agent
    environment:
      ## SSH support. Uncomment volumes -> # - ${SSH_AUTH_SOCK}:/ssh-agent
      - SSH_AUTH_SOCK=/ssh-agent
      - WEB_ROOT
      ### WARNING: Use only if you not use custom php.ini.
      - PHP_SENDMAIL_PATH=${PHP_SENDMAIL_PATH}
      - PHP_SENDMAIL_DOMAIN=${PHP_SENDMAIL_DOMAIN}
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-1}
      - XDEBUG_IDEKEY=${XDEBUG_IDEKEY:-STARK}
      - XDEBUG_HOST
      - PHP_SENDMAIL_DOMAIN
      - PHP_MEMORY_LIMIT
    working_dir: /var/www/html
    labels:
      - 'traefik.port=80'
      - 'traefik.backend=${PROJECT_NAME}_web'
      - 'traefik.frontend.rule=HostRegexp:${PROJECT_URL}, {subdomain:[^.]+}.${PROJECT_URL}'
  mysql:
    image: keopx/${MYSQL_TYPE}:${MYSQL_VERSION}
    container_name: "${PROJECT_NAME}_${MYSQL_HOST}"
    network_mode: traefik_default
    #      volumes:
    #        - ${MYSQL_DATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  redis:
    image: keopx/redis:${REDIS_VERSION}
    container_name: "${PROJECT_NAME}_redis"
    labels:
      - 'traefik.backend=${PROJECT_NAME}_redis'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.redis.localhost'
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    network_mode: traefik_default
    environment:
      - PMA_USER=${MYSQL_ROOT_USER:-root}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=${PROJECT_NAME}_${MYSQL_HOST}
    labels:
      - 'traefik.backend=${PROJECT_NAME}_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.pma.localhost'
  mail:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    network_mode: traefik_default
    ports:
      - "${MAILHOG_PORT_SMTP}:1025"
      - "${MAILHOG_PORT_WEB}:8025"
    labels:
      - 'traefik.backend=${PROJECT_NAME}_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.mailhog.localhost'
